/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda_citas;

import empleados.empleadosDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author desarrollo8
 */
public class agenda extends javax.swing.JFrame {

    /**
     * Creates new form agenda
     */
    public agenda() {
        initComponents();
          this.setLocationRelativeTo(null);
          Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/checador.png"));
       setIconImage(icon);
        try {
            llenarTablaEmp();
        } catch (Exception ex) {
            Logger.getLogger(agenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        vaciartabla();
       
          jtagenda.getColumnModel().getColumn(0).setMaxWidth(150);
          jtagenda.getColumnModel().getColumn(0).setPreferredWidth(150);
          jtagenda.getColumnModel().getColumn(0).setMaxWidth(150);  
          
          jtagenda.getColumnModel().getColumn(3).setMinWidth(0);
          jtagenda.getColumnModel().getColumn(3).setPreferredWidth(0);
          jtagenda.getColumnModel().getColumn(3).setMaxWidth(0);  
          
          
          Date a=new Date();
          jdfecha.setDate(a);
          
           try {
            obtencita("0");
        } catch (Exception ex) {
            Logger.getLogger(agenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtagenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jcuser = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jdfecha = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Citas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 248, 248));

        jtagenda.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtagenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"07:00 a 07:30", null, null, null},
                {"07:30 a 08:00", null, null, null},
                {"08:00 a 08:30", null, null, null},
                {"08:30 a 09:00", null, null, null},
                {"09:00 a 09:30", null, null, null},
                {"09:30 a 10:00", null, null, null},
                {"10:00 a 10:30", null, null, null},
                {"10:30 a 11:00", null, null, null},
                {"11:00 a 11:30", null, null, null},
                {"11:30 a 12:00", null, null, null},
                {"12:00 a 12:30", null, null, null},
                {"12:30 a 13:00", null, null, null},
                {"13:00 a 13:30", null, null, null},
                {"13:30 a 14:00", null, null, null},
                {"14:00 a 14:30", null, null, null},
                {"14:30 a 15:00", null, null, null},
                {"15:00 a 15:30", null, null, null},
                {"15:30 a 16:00", null, null, null},
                {"16:00 a 16:30", null, null, null},
                {"16:30 a 17:00", null, null, null},
                {"17:00 a 17:30", null, null, null},
                {"17:30 a 18:00", null, null, null},
                {"18:00 a 18:30", null, null, null},
                {"18:30 a 19:00", null, null, null},
                {"19:00 a 19:30", null, null, null},
                {"19:30 a 20:00", null, null, null},
                {"20:00 a 20:30", null, null, null},
                {"20:30 a 21:00", null, null, null},
                {"21:00 a 21:30", null, null, null},
                {"21:30 a 22:00", null, null, null},
                {"22:00 a 22:30", null, null, null}
            },
            new String [] {
                "Hora", "Cliente", "Observacion", "IdMov"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtagenda.setRowHeight(20);
        jtagenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtagenda);

        jLabel1.setText("Usuario Atendera:");

        jcuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona.." }));
        jcuser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcuserItemStateChanged(evt);
            }
        });
        jcuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcuserMouseReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario.png"))); // NOI18N
        jButton1.setText("Nueva Cita");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jdfecha.setDateFormatString("yyyy/MM/d");
        jdfecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jdfecha.setName("jdateinicio"); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BuscarIcon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcuser, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcuser, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcuserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcuserItemStateChanged
        // TODO add your handling code here:
        //CAMBIO DE USUARIO
        
    }//GEN-LAST:event_jcuserItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          nueva_cita cita=new nueva_cita(this, false);
        cita.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String user=jcuser.getSelectedItem().toString();
        //if(user.equals("Selecciona..")){        
        //}else{
            //String[] parts = user.split("-");
            //String id = parts[0]; 
            //String nombre = parts[1]; 
            //System.out.println("id: "+id);
            String id="0";
            try {
                obtencita(id);
            } catch (Exception ex) {
                Logger.getLogger(agenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        //}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcuserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcuserMouseReleased
        // TODO add your handling code here:
        String user=jcuser.getSelectedItem().toString();
        if(user.equals("Selecciona..")){        
        }else{
            String[] parts = user.split("-");
            String id = parts[0]; 
            String nombre = parts[1]; 
            System.out.println("id: "+id);
            try {
                obtencita(id);
            } catch (Exception ex) {
                Logger.getLogger(agenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcuserMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int fila=-1;          
         fila=jtagenda.getSelectedRow();
          if(fila!=-1){             
              int opc=JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar?","Alerta",JOptionPane.INFORMATION_MESSAGE);
              if(opc==JOptionPane.OK_OPTION){   
                  String id=jtagenda.getValueAt(jtagenda.getSelectedRow(),3).toString();                    
                  System.out.println(""+id);
                   empleadosDAO control=new empleadosDAO();              
                  try {
                      control.borrarcita(id);
                       String user=jcuser.getSelectedItem().toString();
                        if(user.equals("Selecciona..")){        
                        }else{
                            String[] parts = user.split("-");
                            String idss = parts[0];                              
                            System.out.println("id: "+id);
                            try {
                                obtencita(idss);
                            } catch (Exception ex) {
                                Logger.getLogger(agenda.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                  } catch (Exception ex) {
                      Logger.getLogger(agenda.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  
                
              
              }   
          }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un registro de la tabla.","Alerta",JOptionPane.ERROR_MESSAGE);
         }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agenda().setVisible(true);
            }
        });
    }

    public void llenarTablacitas() throws Exception{
       jtagenda.removeAll(); 
       empleadosDAO control=new empleadosDAO();
       ResultSet res= control.obtenusuarioagenda();
           String[] datosTabla={"Id", "Nombre", "Costo","PAQUETE","Comision x sesion"};
           DefaultTableModel datos = new DefaultTableModel(null, datosTabla);
           while(res.next()){                             
                datos.addRow(new Object[]{res.getString("Id"),res.getString("nombre"),res.getString("Costo"),res.getString("paquete"),res.getString("comision")});
           }
           res.close();           
          jtagenda.setModel(datos);           
          jtagenda.getTableHeader().setReorderingAllowed(false);          
          
          jtagenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                                      
    }   
    public void llenarTablaEmp() throws Exception{
     
       empleadosDAO control=new empleadosDAO();
       ResultSet res= control.obtenusuarioagenda();     
       while(res.next()){     
            jcuser.addItem(res.getString("idusuario")+"-"+res.getString("nombre"));              
       }
       res.close();                                                           
    }

public void vaciartabla(){
        //vacia tabla excepción cliente
        DefaultTableModel modelo=(DefaultTableModel) jtagenda.getModel();         
        for (int i = 0; i < jtagenda.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
        }    
    }
public void obtencita(String idusuario) throws Exception{     
    vaciartabla();
    empleadosDAO control=new empleadosDAO();
    DefaultTableModel modelo=(DefaultTableModel) jtagenda.getModel();       
    String fecha=new SimpleDateFormat("yyyy-MM-dd").format(jdfecha.getDate());
    ResultSet res=control.obtencitasuser(fecha+" 00:00",idusuario,fecha+" 23:50");
    while(res.next()){    
            Date a=res.getTime("fecha_inicia");
            Date b=res.getTime("fecha_finaliza");
            String nota=res.getString("nota");
            String cliente=res.getString("cliente");
            String id_agenda=res.getString("id_agenda");
            SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
            String a1 = df.format(a);
            String b1 = df.format(b);
            modelo.addRow(new Object[]{a+" a "+b,cliente,nota,""+id_agenda});
    }
    
     /*
    ResultSet res=control.obtencitas(fecha+" 07:00",idusuario,fecha+" 07:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 0, 1);        
    }     
   
    res=control.obtencitas(fecha+" 07:30",idusuario,fecha+" 08:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 1, 1);
    }    
    res=control.obtencitas(fecha+" 08:00",idusuario,fecha+" 08:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 2, 1);
    }
    res=control.obtencitas(fecha+" 08:30",idusuario,fecha+" 09:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 3, 1);
    }
    res=control.obtencitas(fecha+" 09:00",idusuario,fecha+" 09:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 4, 1);
    }
    res=control.obtencitas(fecha+" 09:30",idusuario,fecha+" 10:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 5, 1);
    }    
    res=control.obtencitas(fecha+" 10:00",idusuario,fecha+" 10:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 6, 1);
    }
    res=control.obtencitas(fecha+" 10:30",idusuario,fecha+" 11:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 7, 1);
    }
    res=control.obtencitas(fecha+" 11:00",idusuario,fecha+" 11:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 8, 1);
    }
    res=control.obtencitas(fecha+" 11:30",idusuario,fecha+" 12:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 9, 1);
    }
    res=control.obtencitas(fecha+" 12:00",idusuario,fecha+" 12:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 10, 1);
    }
    res=control.obtencitas(fecha+" 12:30",idusuario,fecha+" 13:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 11, 1);
    }
    res=control.obtencitas(fecha+" 13:00",idusuario,fecha+" 13:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 12, 1);
    }
    res=control.obtencitas(fecha+" 13:30",idusuario,fecha+" 14:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 13, 1);
    }
    res=control.obtencitas(fecha+" 14:00",idusuario,fecha+" 14:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 14, 1);
    }
    res=control.obtencitas(fecha+" 14:30",idusuario,fecha+" 15:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 15, 1);
    }
    res=control.obtencitas(fecha+" 15:00",idusuario,fecha+" 15:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 16, 1);
    }
    res=control.obtencitas(fecha+" 15:30",idusuario,fecha+" 16:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 17, 1);
    }
    res=control.obtencitas(fecha+" 16:00",idusuario,fecha+" 16:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 18, 1);
    }
    res=control.obtencitas(fecha+" 16:30",idusuario,fecha+" 17:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 19, 1);
    }
    res=control.obtencitas(fecha+" 17:00",idusuario,fecha+" 17:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 20, 1);
    }
    res=control.obtencitas(fecha+" 17:30",idusuario,fecha+" 18:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 21, 1);
    }
    res=control.obtencitas(fecha+" 18:00",idusuario,fecha+" 18:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 22, 1);
    }
    res=control.obtencitas(fecha+" 18:30",idusuario,fecha+" 19:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 23, 1);
    }
    res=control.obtencitas(fecha+" 19:00",idusuario,fecha+" 19:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 24, 1);
    }
    res=control.obtencitas(fecha+" 19:30",idusuario,fecha+" 20:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 25, 1);
    }
    res=control.obtencitas(fecha+" 20:00",idusuario,fecha+" 20:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 26, 1);
    }
    res=control.obtencitas(fecha+" 20:30",idusuario,fecha+" 21:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 27, 1);
    }
    res=control.obtencitas(fecha+" 21:00",idusuario,fecha+" 21:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 28, 1);
    }
    res=control.obtencitas(fecha+" 21:30",idusuario,fecha+" 22:00");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 29, 1);
    }
    res=control.obtencitas(fecha+" 22:00",idusuario,fecha+" 22:30");
    if(res.next()){    
        jtagenda.setValueAt(res.getString("cliente"), 30, 1);
    }
*/
}    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcuser;
    private com.toedter.calendar.JDateChooser jdfecha;
    private javax.swing.JTable jtagenda;
    // End of variables declaration//GEN-END:variables
}
