/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda_citas;

import empleados.empleadosDAO;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author desarrollo8
 */
public class nueva_cita extends javax.swing.JDialog {

    /**
     * Creates new form nueva_cita
     */
    public nueva_cita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date a=new Date();
        jdfecha.setDate(a);
        this.setLocationRelativeTo(null);
        try {
            llenarTablaEmp();
            llenarTablaclientes();
        } catch (Exception ex) {
            Logger.getLogger(nueva_cita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jccliente = new javax.swing.JComboBox<>();
        jcuser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnota = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jdfecha = new com.toedter.calendar.JDateChooser();
        jchora = new javax.swing.JComboBox<>();
        jcduracion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Cita");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 248, 248));

        jLabel1.setText("Cliente:");

        jLabel2.setText("Usuario Atendera:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Hora Ingresa:");

        jLabel5.setText("Nota:");

        jccliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona.." }));

        jcuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona.." }));

        txtnota.setColumns(20);
        txtnota.setRows(5);
        jScrollPane1.setViewportView(txtnota);

        jLabel6.setText("Duración Session:");

        jdfecha.setDateFormatString("yyyy/MM/d");
        jdfecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jdfecha.setName("jdateinicio"); // NOI18N

        jchora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00" }));

        jcduracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jccliente, 0, 245, Short.MAX_VALUE)
                                    .addComponent(jcuser, 0, 245, Short.MAX_VALUE)
                                    .addComponent(jchora, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jcduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jccliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jchora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nota=txtnota.getText().trim();
        String hora=jchora.getSelectedItem().toString();
        String duracion=jcduracion.getSelectedItem().toString();        
        int dura=Integer.parseInt(obtenminutos(duracion));  
        String clien=jccliente.getSelectedItem().toString();
        String user=jcuser.getSelectedItem().toString();
        if(clien.equals("Selecciona..")){        
            JOptionPane.showMessageDialog(null,"Selecciona un cliente.","Mensaje",JOptionPane.ERROR_MESSAGE);
        }else if(user.equals("Selecciona..")){        
            JOptionPane.showMessageDialog(null,"Selecciona un usuario.","Mensaje",JOptionPane.ERROR_MESSAGE);
        }else if(jdfecha.getDate()==null){
            JOptionPane.showMessageDialog(null,"Falta ingresar la fecha.","Mensaje",JOptionPane.ERROR_MESSAGE);
        }else{
            String[] parts = user.split("-");
            String idusers = parts[0];                         
            String[] partcliente = clien.split("-");
            String idcliente = partcliente[0];             
            
            String fechaini=new SimpleDateFormat("yyyy-MM-dd").format(jdfecha.getDate());
            fechaini=fechaini+" "+hora;
            System.out.println(""+fechaini);
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm");           
            try {
                Date fec=null;
                fec = formatter.parse(fechaini);                               
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(fec); //tuFechaBase es un Date;
                calendar.add(Calendar.MINUTE, dura); //minutosASumar es int.
                Date fechaSalida = calendar.getTime(); //Y ya tienes la fecha sumada.
                String fechafin=new SimpleDateFormat("yyyy-MM-dd HH:mm").format(fechaSalida);
                System.out.println(""+fechafin);
                empleadosDAO control=new empleadosDAO();
            try {
                control.guardarcita(idusers,idcliente,fechaini,fechafin,nota);
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(nueva_cita.class.getName()).log(Level.SEVERE, null, ex);
            }
            } catch (ParseException ex) {
                Logger.getLogger(nueva_cita.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nueva_cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nueva_cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nueva_cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nueva_cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nueva_cita dialog = new nueva_cita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jccliente;
    private javax.swing.JComboBox<String> jcduracion;
    private javax.swing.JComboBox<String> jchora;
    private javax.swing.JComboBox<String> jcuser;
    private com.toedter.calendar.JDateChooser jdfecha;
    private javax.swing.JTextArea txtnota;
    // End of variables declaration//GEN-END:variables

 public void llenarTablaEmp() throws Exception{
     
       empleadosDAO control=new empleadosDAO();
       ResultSet res= control.obtenusuarioagenda();     
       while(res.next()){     
            jcuser.addItem(res.getString("idusuario")+"-"+res.getString("nombre"));              
       }
       res.close();                                                           
    }
 
 
 public void llenarTablaclientes() throws Exception{
     
       empleadosDAO control=new empleadosDAO();
       ResultSet res= control.obtenclientes();     
       while(res.next()){     
            jccliente.addItem(res.getString("id_empleado")+"-"+res.getString("cliente"));              
       }
       res.close();                                                           
    }

 











 public String obtenminutos(String tiempo){
     String minutos="0";
     if(tiempo.equals("00:30")){
         minutos="30";
     }
     if(tiempo.equals("01:00")){
         minutos="60";
     }
     if(tiempo.equals("01:30")){
         minutos="90";
     }
     if(tiempo.equals("02:00")){
         minutos="120";
     }
     if(tiempo.equals("02:30")){
         minutos="150";
     }     
     if(tiempo.equals("03:00")){
         minutos="180";
     }
     if(tiempo.equals("03:30")){
         minutos="210";
     }
     if(tiempo.equals("04:00")){
         minutos="240";
     }
     if(tiempo.equals("04:30")){
         minutos="270";
     }
     if(tiempo.equals("05:00")){
         minutos="300";
     }     
     if(tiempo.equals("05:30")){
         minutos="330";
     }
     if(tiempo.equals("06:00")){
         minutos="360";
     }
     return minutos;    
 }
}
