/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package empleados;
import Formularios.CapturaHuella;
import camptura_fotook.captura_foto;
import capturafoto.frmPrincipal;
import capturafoto.obtenerfoto;
import checador.accesoSistema;
import conex.conexion;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JOSE
 */







public class cat_empleados extends javax.swing.JDialog {
private static TableRowSorter<TableModel> sorter;
    /**
     * Creates new form cat_empleados
     */
    public cat_empleados(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/checador.png"));
       setIconImage(icon);
    try {
        llenarTablaEmp();
    } catch (Exception ex) {
        Logger.getLogger(cat_empleados.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbfoto = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jltotal = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtempleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlsocios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpagos = new javax.swing.JTable();
        txtidsocio = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catálogo de socios");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar por: Nombre/Clave:");

        txtbusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscaKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddSmall.png"))); // NOI18N
        jButton1.setText("Nuevo");
        if(accesoSistema.licencia.equals("DEMO")){
            jButton1.setVisible(false);
        }
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/huella.png"))); // NOI18N
        jButton3.setText("Huella");
        if(accesoSistema.licencia.equals("DEMO")){
            //jButton3.setVisible(false);
        }
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camara.gif"))); // NOI18N
        if(accesoSistema.licencia.equals("DEMO")){
            //jButton4.setVisible(false);
        }
        jButton4.setText("Foto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lbfoto.setBackground(new java.awt.Color(255, 153, 0));
        lbfoto.setText("FOTO DEL SOCIO");
        lbfoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        jButton5.setText("Registrar Entrada Manualmente");
        jButton5.setVisible(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jltotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jltotal.setText("Activos:");

        jButton8.setText("Eliminar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Exportar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 270, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(lbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtempleados.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jtempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Edad", "telefono", "correo", "Fecha_registro", "fecha_vencimiento", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtempleados.setRowHeight(20);
        jtempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtempleadosMouseClicked(evt);
            }
        });
        jtempleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtempleadosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtempleados);

        jPanel3.setBackground(new java.awt.Color(243, 239, 239));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("SOCIO:");

        jlsocios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlsocios.setForeground(new java.awt.Color(0, 102, 153));

        jtpagos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtpagos.getTableHeader().setReorderingAllowed(false);
        jtpagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id pago", "Fecha Pago", "Monto", "Tratamiento", "Comentario", "Fecha Vencimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtpagos.setRowHeight(22);
        jtpagos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jtpagos);

        txtidsocio.setVisible(false);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton6.setText("Pagar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        jButton7.setText("Eliminar");
        if(accesoSistema.licencia.equals("DEMO")){
            jButton7.setVisible(false);
        }
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlsocios, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidsocio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlsocios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtidsocio)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        registro_empleados emp=new registro_empleados();
        emp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyPressed
        // TODO add your handling code here:
        txtbusca.getDocument().addDocumentListener(new DocumentListener(){
          @Override
          public void insertUpdate(DocumentEvent e) {
              filtrar();
          }
          @Override
          public void removeUpdate(DocumentEvent e) {
              filtrar();
          }
          @Override
          public void changedUpdate(DocumentEvent e) {
              filtrar();
          }
        });
    }//GEN-LAST:event_txtbuscaKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
        int fila=-1;
	fila=jtempleados.getSelectedRow();
	if(fila!=-1){
            String id=jtempleados.getValueAt(jtempleados.getSelectedRow(), 0).toString();
            System.out.println(""+id);
            captura_foto tomarfoto=new captura_foto(id);
            tomarfoto.setVisible(true);
            //frmPrincipal tomafoto=new frmPrincipal(id);
            //tomafoto.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione una empleado de la tabla para agregar la foto","Alerta",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
	fila=jtempleados.getSelectedRow();
	if(fila!=-1){
            String id=jtempleados.getValueAt(jtempleados.getSelectedRow(), 0).toString();
            System.out.println(""+id);
            CapturaHuella huella= new CapturaHuella(id);
            huella.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione una empleado de la tabla para agregar la huella","Alerta",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtempleadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtempleadosKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtempleadosKeyPressed

    private void jtempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtempleadosMouseClicked
        // TODO add your handling code here:
        
       if(evt.getClickCount()==2){
          System.out.println("Se ha hecho doble click");         
          int fila=-1;
           fila=jtempleados.getSelectedRow();

               String id=jtempleados.getValueAt(jtempleados.getSelectedRow(), 0).toString();
               String nombre=jtempleados.getValueAt(jtempleados.getSelectedRow(), 1).toString();
               System.out.println(""+id);


           conexion con=new conexion();
           Statement st1=null;
               try {
                   st1 = con.getConnection().createStatement();
               } catch (SQLException ex) {

               }
           try {                 
               ResultSet rs = st1.executeQuery("SELECT Imagen FROM tc_empleados where id_empleado="+id);
               while (rs.next())
                   {
                           if(rs.getBlob("Imagen")==null){
                               System.out.println("nullo");
                                lbfoto.setIcon(null);
                           }else{
                               Blob blob = rs.getBlob("Imagen");			
                               byte[] data = blob.getBytes(1, (int)blob.length());
                               System.out.println("data:"+data);
                               BufferedImage img = null;
                               try {
                                       img = ImageIO.read(new ByteArrayInputStream(data));
                               } catch (IOException ex) {

                               }
                               ImageIcon imageIcon = new ImageIcon(img);
                               //lbfoto.setIcon(imageIcon);
                               lbfoto.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(184,140,Image.SCALE_SMOOTH)));
                           }
                   }
                   rs.close();
                   st1.close();
           } catch (SQLException ex) {
               Logger.getLogger(obtenerfoto.class.getName()).log(Level.SEVERE, null, ex);
           }

          con.desconectar();


          obtenpagos(id,nombre);
       }
    }//GEN-LAST:event_jtempleadosMouseClicked

    public static void vaciartabla(){
        DefaultTableModel modelo=(DefaultTableModel) jtpagos.getModel();         
            for (int i = 0; i < jtpagos.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }  
    public static void obtenpagos(String id,String nombre){
      jlsocios.setText(nombre);
      txtidsocio.setText(id);
      
      
      DefaultTableModel modelo;
      modelo=(DefaultTableModel) jtpagos.getModel();      
      vaciartabla();    
      
      conexion con=new conexion();
        Statement st1=null;          
        try {   
            st1 = con.getConnection().createStatement();
            ResultSet rs = st1.executeQuery("SELECT * FROM to_pagos where idr_empleado="+id+" order by Idpago desc");
            while (rs.next())
		{
			modelo.addRow(new Object[]{""+rs.getString("Idpago"),""+rs.getString("fecha_pago"),"$"+rs.getString("monto"),""+rs.getString("tratamiento"),""+rs.getString("comentario"),""+rs.getString("fecha_vence")});
                }
		rs.close();
                st1.close();
        } catch (SQLException ex) {
            Logger.getLogger(obtenerfoto.class.getName()).log(Level.SEVERE, null, ex);
        }
                       
       con.desconectar();
      
       
       
       
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
	fila=jtempleados.getSelectedRow();
	if(fila!=-1){
            String id=jtempleados.getValueAt(jtempleados.getSelectedRow(), 0).toString();
            System.out.println(""+id);
            edicion_empleados edicion=new edicion_empleados(id);
            edicion.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un socio de la tabla para modificar","Alerta",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        int fila=-1;
	fila=jtempleados.getSelectedRow();
	if(fila!=-1){
            String id=jtempleados.getValueAt(jtempleados.getSelectedRow(), 0).toString();
            String nombre=jtempleados.getValueAt(jtempleados.getSelectedRow(), 1).toString()+" "+jtempleados.getValueAt(jtempleados.getSelectedRow(), 2).toString()+" "+jtempleados.getValueAt(jtempleados.getSelectedRow(), 3).toString();
            String rfc=jtempleados.getValueAt(jtempleados.getSelectedRow(), 4).toString();
            System.out.println(""+id);
            registro_entrada_manual edicion=new registro_entrada_manual(id,nombre,rfc);
            edicion.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un empleado de la tabla para registrar entrada","Alerta",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String idsocio=txtidsocio.getText().trim();
        if(idsocio.equals("")){
            JOptionPane.showMessageDialog(null,"Seleccione un socio de la tabla para registrar el pago.","Alerta",JOptionPane.ERROR_MESSAGE);
        }else{
            Frame f = JOptionPane.getFrameForComponent(this);
            EntradaEfectivo dialog = new EntradaEfectivo(f, true, idsocio, jlsocios.getText().trim());
            dialog.show();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
	fila=jtpagos.getSelectedRow();
	if(fila!=-1){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog (null, "Desea eliminar el pago?","Warning",dialogButton);

            if(dialogButton == JOptionPane.YES_OPTION){ //The ISSUE is here
                String id=jtpagos.getValueAt(jtpagos.getSelectedRow(), 0).toString();
                System.out.println(""+id);
                conexion cn = new conexion();
                String sql="delete from to_pagos where Idpago="+id;
                System.out.println(sql);
                PreparedStatement pstm100;
                try {
                        pstm100 = (PreparedStatement) cn.getConnection().prepareStatement(sql);
                        pstm100.executeUpdate();
                        String fechavence="";
                        pstm100 = (PreparedStatement) cn.getConnection().prepareStatement("select fecha_vence from to_pagos where idr_empleado='"+txtidsocio.getText()+"' order by Idpago desc limit 1");
                        ResultSet rs=pstm100.executeQuery(); 
                        while(rs.next()){
                            fechavence=rs.getString("fecha_vence");
                        }
                        if(!fechavence.equals("")){
                            pstm100 = (PreparedStatement) cn.getConnection().prepareStatement("update tc_empleados set fecha_vencimiento='"+fechavence+"' where id_empleado="+txtidsocio.getText());
                            pstm100.executeUpdate();
                        }else{
                            pstm100 = (PreparedStatement) cn.getConnection().prepareStatement("update tc_empleados set fecha_vencimiento=null where id_empleado="+txtidsocio.getText());
                            pstm100.executeUpdate();
                        }
                        
                        rs.close();
                        pstm100.close();
                        
                        
                        
                        obtenpagos(txtidsocio.getText(),jlsocios.getText());
                        try {
                            llenarTablaEmp();
                        } catch (Exception ex) {
                            Logger.getLogger(EntradaEfectivo.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null,"El pago se elimino correctamente.","Ok",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e2) {
                        // TODO Auto-generated catch block
                        JOptionPane.showMessageDialog(null,"No se pudo eliminar el pago.","ERROR",JOptionPane.ERROR_MESSAGE);
                        e2.printStackTrace();
                }           
                cn.desconectar();                     
            }
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione el pago a eliminar.","Alerta",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
	fila=jtempleados.getSelectedRow();
	if(fila!=-1){
            String id=jtempleados.getValueAt(jtempleados.getSelectedRow(), 0).toString();
            System.out.println(""+id);
            
            
            conexion cn = new conexion();
                String sql="delete from tc_empleados where id_empleado="+id;
                System.out.println(sql);
                PreparedStatement pstm100;
                try {
                        pstm100 = (PreparedStatement) cn.getConnection().prepareStatement(sql);
                        pstm100.executeUpdate();                                                
                        pstm100.close();         
                        try {
                            llenarTablaEmp();
                        } catch (Exception ex) {
                            Logger.getLogger(cat_empleados.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null,"El socio se elimino correctamente.","Ok",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e2) {                        
                        JOptionPane.showMessageDialog(null,"No se pudo eliminar el socio.","ERROR",JOptionPane.ERROR_MESSAGE);
                        e2.printStackTrace();
                }           
                cn.desconectar();     
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un socio de la tabla para eliminar","Alerta",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
            Date fecha1=new Date();
            SimpleDateFormat formateador = new SimpleDateFormat("dd-MM-yyyy hh-MM-ss");
            //formateador.format(fecha1);
            System.out.println(formateador.format(fecha1));  
            System.out.println(fecha1.toLocaleString());
            File archivo;
            javax.swing.JFileChooser jF1= new javax.swing.JFileChooser(); 
            String ruta = ""; 
            try{ 
            if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){ 
            ruta = jF1.getSelectedFile().getAbsolutePath();
            //archivo = new File(ruta+""+formateador.format(fecha1)+".xls");
            archivo = new File(ruta+".xls");
            System.out.println(archivo);
            //Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras...
            exportarjTable(jtempleados,archivo);
            JOptionPane.showMessageDialog(null, "El reporte se ha generado con exito", "Mensaje", JOptionPane.DEFAULT_OPTION);
            } 
            }catch (Exception ex){ 
                    JOptionPane.showMessageDialog(null, "No se ha podido generar el archivo:"+ex, "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
            }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cat_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cat_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cat_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cat_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new cat_empleados().setVisible(true);
            }
        });
    }

    public static void llenarTablaEmp() throws Exception{
       jtempleados.removeAll(); 
       empleadosDAO control=new empleadosDAO();
       ResultSet res= control.obtenerEmpleados();
           String[] datosTabla={"Id", "Nombre", "Edad", "Telefono", "Correo", "Fecha registro", "Fecha vencimiento","Estatus"};
           DefaultTableModel datos = new DefaultTableModel(null, datosTabla);
           int activos=0;
           while(res.next()){               
               String estatus="ACTIVO";
               if(res.getInt("fecha")>=0){
                   activos++;
               }
               if(res.getInt("fecha")<0){
                    estatus="VENCIDO";
               }
               if(res.getString("fecha")==null){
                    estatus="VENCIDO";
               }
                datos.addRow(new Object[]{res.getString("id_empleado"),res.getString("nombre")+" "+res.getString("apaterno")+" "+res.getString("amaterno"),res.getString("edad")+" años",res.getString("telefono"),res.getString("correo"),res.getString("fecha_registro"),res.getString("fecha_vencimiento"),estatus});
           }
           jltotal.setText("ACTIVOS: "+activos);
           res.close();
            jtempleados.setModel(datos);
           
           jtempleados.getTableHeader().setReorderingAllowed(false);          
          sorter = new TableRowSorter<TableModel>(datos);
          jtempleados.setRowSorter(sorter);
          jtempleados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
          jtempleados.getColumnModel().getColumn(0).setMaxWidth(70);
          jtempleados.getColumnModel().getColumn(2).setPreferredWidth(120);
          jtempleados.getColumnModel().getColumn(2).setMaxWidth(120);
          jtempleados.getColumnModel().getColumn(5).setPreferredWidth(120);
          jtempleados.getColumnModel().getColumn(5).setMaxWidth(120);
          jtempleados.getColumnModel().getColumn(6).setPreferredWidth(120);
          jtempleados.getColumnModel().getColumn(6).setMaxWidth(120);
          jtempleados.getColumnModel().getColumn(7).setPreferredWidth(120);
          jtempleados.getColumnModel().getColumn(7).setMaxWidth(120);
           
    }
    
    
    private void filtrar() {
         RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter("(?i)"+txtbusca.getText(),1,2,3,4);
        }catch (java.util.regex.PatternSyntaxException e) {
        }
        sorter.setRowFilter(rf);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel jlsocios;
    private static javax.swing.JLabel jltotal;
    private static javax.swing.JTable jtempleados;
    private static javax.swing.JTable jtpagos;
    private javax.swing.JLabel lbfoto;
    private javax.swing.JTextField txtbusca;
    private static javax.swing.JTextField txtidsocio;
    // End of variables declaration//GEN-END:variables

public void exportarjTable(JTable tabla, File ficheroXLS) throws IOException {
        TableModel modelo = tabla.getModel();
        FileWriter fichero = new FileWriter(ficheroXLS);
        
        for(int i=0; i < modelo.getColumnCount(); i++) {
            fichero.write(modelo.getColumnName(i) + "\t");
        }
        fichero.write("\n");
        for(int i=0; i< modelo.getRowCount(); i++) {
            for(int j=0; j < modelo.getColumnCount(); j++) {
                fichero.write(modelo.getValueAt(i,j).toString()+"\t");
            }
            fichero.write("\n");
        }
        fichero.close();
    }

}
