/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checador;

import conex.conexion;
import empleados.Ticket;
import empleados.empleadosDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author desarrollo8
 */
public class SesionesSpa extends javax.swing.JDialog {
String nombrecliente="",idclientefinal="";

    /**
     * Creates new form SesionesSpa
     */
    public SesionesSpa(java.awt.Frame parent, boolean modal,String idcliente,String nombre) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        idclientefinal=idcliente;
        nombrecliente=nombre;
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/checador.png"));
        setIconImage(icon); 
        
        lblnombre.setText(nombre);
            try {
                cargatabla(idcliente);
            } catch (Exception ex) {
                Logger.getLogger(SesionesSpa.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
             conexion con = new conexion();
             Statement st = null;
             ResultSet  resultado= null;
              try {  
                    st = con.getConnection().createStatement();
                    resultado=st.executeQuery("select * from tc_usuarios where estatus=1");                    
                    while(resultado.next()){               
                        jcusuario.addItem(resultado.getString("idusuario")+"-"+resultado.getString("nombre"));                        
                    }           
                   resultado.close();
                    con.desconectar();
                } catch (SQLException ex) {
                    Logger.getLogger(SesionesSpa.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtempleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                if(colIndex==4){ //Con esto se pueden editar todas las celdas menos la de la columna 0  colIndex==7 ||
                    return true;
                }
                else{
                    return false;
                }

                //return false; //Disallow the editing of any cell
            }
        };
        jButton1 = new javax.swing.JButton();
        jcusuario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 246, 247));

        lblnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnombre.setText("Cliente");

        jtempleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Mov", "Tratamiento", "Sesiones", "Comision", "Marcar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtempleados.setRowHeight(22);
        jScrollPane1.setViewportView(jtempleados);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceptar_.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona.." }));

        jLabel1.setText("Atendio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcusuario, 0, 212, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcusuario)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user=jcusuario.getSelectedItem().toString();
        if(user.equals("Selecciona..")){
          JOptionPane.showMessageDialog(null, "Debe seleccionar le persona que atendio.", "Alerta", JOptionPane.ERROR_MESSAGE);  
        }else{
            String[] datos = user.split("-");
            String iduser=datos[0];
            String nombre=datos[1];
            
            int fila=-1;                        
            fila=jtempleados.getSelectedRowCount();    
            if(fila>0){       
                 conexion con = new conexion();
                 Statement st = null;
                 ResultSet  resultado= null;

                        //int[] row_indexes=jtempleados.getSelectedRows();
                        for(int i=0; i<jtempleados.getRowCount(); i++){    
                        //for(int i=0;i<row_indexes.length;i++){    
                            System.out.println("aa:"+jtempleados.getValueAt(i, 4));
                        if(jtempleados.getValueAt(i, 4)==null){
                        
                        }else{
                            String val=jtempleados.getValueAt(i, 4).toString(); 
                            System.out.println(""+val);
                            if(val.equals("true")){
                                /*String idsesion=jtempleados.getValueAt(row_indexes[i], 0).toString();
                                String tratamiento=jtempleados.getValueAt(row_indexes[i], 1).toString();
                                String comision=jtempleados.getValueAt(row_indexes[i], 3).toString();*/
                                String idsesion=jtempleados.getValueAt(i, 0).toString();
                                String tratamiento=jtempleados.getValueAt(i, 1).toString();
                                String comision=jtempleados.getValueAt(i, 3).toString();
                                System.out.println("idsesion:"+idsesion);   
                               try {  
                                   st = con.getConnection().createStatement();
                                   st.executeUpdate("insert into to_movimientos (id_emp,nombre,fecha_entrada,fecha_movimiento,fecha_salida,motivo,idrusuario,comision) values('"+idclientefinal+"','"+nombrecliente+"',now(),now(),now(),'"+tratamiento+"','"+iduser+"','"+comision+"')");
                                   st.executeUpdate("update to_pagos set sesiones_realizadas=sesiones_realizadas-1 where idr_empleado='"+idclientefinal+"' and IdPago='"+idsesion+"'");                                                        

                                   Ticket imprime=new Ticket();                    
                                   imprime.imprimirentrada(nombrecliente,tratamiento);

                               } catch (SQLException ex) {
                                   Logger.getLogger(SesionesSpa.class.getName()).log(Level.SEVERE, null, ex);
                               }
                            }
                         }
                        }    
                        con.desconectar();
                        JOptionPane.showMessageDialog(null, "Se descontaron las sesiones del cliente.", "OK", JOptionPane.INFORMATION_MESSAGE);                                                    
                        dispose();
            }else{
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna sesion de la tabla.", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionesSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionesSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionesSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionesSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SesionesSpa dialog = new SesionesSpa(new javax.swing.JFrame(), true,"","");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcusuario;
    private javax.swing.JTable jtempleados;
    private javax.swing.JLabel lblnombre;
    // End of variables declaration//GEN-END:variables


public void cargatabla(String id) throws Exception{
       jtempleados.removeAll(); 
       empleadosDAO control=new empleadosDAO();
       ResultSet res= control.obtensesiones(id);
           //String[] datosTabla={"Id Mov","Tratamiento", "Sesiones","Comision","Marcar"};
           DefaultTableModel datos=(DefaultTableModel) jtempleados.getModel(); 
           //DefaultTableModel datos = new DefaultTableModel(null, datosTabla);
           int activos=0;
           while(res.next()){               
               
                datos.addRow(new Object[]{res.getString("Idpago"),res.getString("tratamiento"),res.getString("sesiones_realizadas"),res.getString("comision"),false});
           }           
           res.close();
           jtempleados.setModel(datos);           
           jtempleados.getTableHeader().setReorderingAllowed(false);          
           jtempleados.getColumnModel().getColumn(0).setPreferredWidth(0);
           jtempleados.getColumnModel().getColumn(0).setMinWidth(0);
           jtempleados.getColumnModel().getColumn(0).setMaxWidth(0);
           
           jtempleados.getColumnModel().getColumn(2).setPreferredWidth(105);
           jtempleados.getColumnModel().getColumn(2).setMinWidth(105);
           jtempleados.getColumnModel().getColumn(2).setMaxWidth(105);
           
           jtempleados.getColumnModel().getColumn(3).setPreferredWidth(0);
           jtempleados.getColumnModel().getColumn(3).setMinWidth(0);
           jtempleados.getColumnModel().getColumn(3).setMaxWidth(0);
           
    }
}
