/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package camptura_fotook;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.github.sarxos.webcam.WebcamUtils;
import com.github.sarxos.webcam.util.ImageUtils;
import conex.conexion;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author jose
 */
public class captura_foto extends javax.swing.JFrame {
        private String idemp="";
	Webcam webcam = Webcam.getDefault();
	Dimension[] nonStandardResolutions = new Dimension[] {
			WebcamResolution.PAL.getSize(),
			WebcamResolution.HD720.getSize(),
			new Dimension(2000, 1000),
			new Dimension(1000, 500),
		};
    /**
     * Creates new form camptura_foto
     */
    public captura_foto(String id) {
        idemp=id;
        webcam.setCustomViewSizes(nonStandardResolutions);
        webcam.setViewSize(WebcamResolution.HD720.getSize());
        webcam.open();
        initComponents();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FormWindowClose(evt);
            }
        });
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        
        jButton1 = new javax.swing.JButton();

		 
		//webcam.setViewSize(WebcamResolution.VGA.getSize());

		jpfoto = new WebcamPanel(webcam);
		jpfoto.setFPSDisplayed(true);
		jpfoto.setDisplayDebugInfo(true);
		
		jpfoto.setImageSizeDisplayed(true);
		jpfoto.setMirrored(true);
        
		
		
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Captura de Foto");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jpfotoLayout = new javax.swing.GroupLayout(jpfoto);
        jpfoto.setLayout(jpfotoLayout);
        jpfotoLayout.setHorizontalGroup(
            jpfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jpfotoLayout.setVerticalGroup(
            jpfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jpfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 690, 430));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camara.gif"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //WebcamUtils.capture(webcam, "foto", ImageUtils.FORMAT_JPG);   
        byte[] bytes = WebcamUtils.getImageBytes(webcam, "jpg");
      

        // save image in JPG format and return as byte buffer
        //ByteBuffer buffer = WebcamUtils.getImageByteBuffer(webcam, "jpg");
        //System.out.println("Buffer length: " + buffer.capacity());
        
         InputStream in=new ByteArrayInputStream(bytes);
         System.out.println(""+in);
         conexion con=new conexion(); 
         String sql = "update tc_empleados set imagen = (?) where id_empleado="+idemp;
         System.out.println(""+sql);
         PreparedStatement stmt = null;
            try {
                stmt = con.getConnection().prepareStatement(sql);
                stmt.setBinaryStream(1,in);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Se registro la foto correctamente","Foto agregada correctamente",JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Error al registrar: "+ex,"Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
         con.desconectar();
         System.out.println("SALIDA DE IMAGEN");
         
         
         
         
         
         
        webcam.close();
        System.out.println("HOLA "+idemp);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

     private void FormWindowClose(java.awt.event.WindowEvent evt) {                                 
         webcam.close();
    }     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(captura_foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(captura_foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(captura_foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(captura_foto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new captura_foto("0").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private WebcamPanel jpfoto;
    // End of variables declaration//GEN-END:variables
}
